on:
  create

jobs:
  create_issue:
    name: Create about Issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create About
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          title: "Create an about file"
          body: |
            Add a file `about.md` that has your name and expected graduation in it

          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
